---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: urplugin-log
  namespace: {{ .Values.urplugin.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: {{ .Values.urplugin.namespace }}
    name: urplugin-log-claim
  hostPath:
    path: {{ .Values.urplugin.logPath }}
