apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: odim
spec:
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - nodePort: 30080
    port: 45000
  selector:
    app: api
  type: NodePort
