apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.odimra.namespace }}
  labels:
    app: api
spec:
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
  - nodePort: {{ .Values.odimra.apiNodePort }}
    port: 45000
  selector:
    app: api
  type: NodePort
